=== lythaiho/Makeup-language-and-JSON/Assignment2/Cart.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="cart" type="noteType"></xsd:element>
    <xsd:complexType name="noteType">
        <xsd:sequence>
            <xsd:element name="Customer" type="CustomerType"></xsd:element>
            <xsd:element name="GrandTotal" type="xsd:integer"></xsd:element>
            <xsd:element name="Date" type="xsd:date"></xsd:element>
            <xsd:element name="Items" type="ItemsType">

            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>

    <!--    CustomerType Start-->
    <xsd:complexType name="CustomerType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"></xsd:element>
            <xsd:element name="address" type="xsd:string"></xsd:element>
            <xsd:element name="tel" type="xsd:integer"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <!--    CustomerType end-->

    <!--    itemsType Start-->
    <xsd:complexType name="ItemsType">
        <xsd:sequence>
            <xsd:element name="Item" minOccurs="1" maxOccurs="unbounded" type="ItemType">

            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <!--    itemsType end-->

    <!--    itemType Start-->
    <xsd:complexType name="ItemType">
        <xsd:sequence>
            <xsd:element name="nameItem" type="xsd:string"></xsd:element>
            <xsd:element name="priceItem" type="xsd:integer"></xsd:element>
            <xsd:element name="quantityItem" type="xsd:integer"></xsd:element>
            <xsd:element name="subTotal" type="xsd:integer"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <!--    itemType end-->

</xsd:schema>

=== lythaiho/Makeup-language-and-JSON/Assignment2/Cart.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="Cart.xsl"?>
<cart xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Cart.xsd">
    <Customer>
        <name>Duy code</name>
        <address>Long Biên- Hà Nội</address>
        <tel>0987654321</tel>
    </Customer>
    <GrandTotal>1000000</GrandTotal>
    <Date>2019-11-29</Date>
    <Items>
        <Item>
            <nameItem>Duy code</nameItem>
            <priceItem>50</priceItem>
            <quantityItem>20</quantityItem>
            <subTotal>10</subTotal>
        </Item>
        <Item>
            <nameItem>Vũ code</nameItem>
            <priceItem>10</priceItem>
            <quantityItem>3</quantityItem>
            <subTotal>20</subTotal>
        </Item>
    </Items>
</cart>
