=== lythaiho/Makeup-language-and-JSON/contact.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="note" type="noteType"></xsd:element>
    <xsd:complexType name="noteType">
        <xsd:sequence>
            <xsd:element name="from" type="xsd:string"></xsd:element>
            <xsd:element name="to" type="xsd:string" minOccurs="1" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="cc" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="heading" type="xsd:string"></xsd:element>
            <xsd:element name="body" >
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="header" type="xsd:integer"></xsd:element>
                        <xsd:element name="main" type="xsd:string"></xsd:element>
                        <xsd:element name="footer" type="xsd:date"></xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== lythaiho/Makeup-language-and-JSON/contact.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="contact.xsl"?>
<note xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="contact.xsd">
    <from>Sender</from>
    <to>Receiver</to>
    <cc>Anyone</cc>
    <cc>Say oh year</cc>
    <heading>Send an email</heading>
    <body>
        <header>1</header>
        <main>Noi dung email</main>
        <footer>2009-09-08</footer>
    </body>
<!--    <content></content>-->
</note>
